export const RECOMMENDED_COURSES: Record<string, { name: string; provider: string; url: string; isFree: boolean }> = {
    "Masonry": { name: "Basic Masonry Techniques", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Mason", isFree: true },
    "Concrete Work": { name: "Concrete Construction & Finishing", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Concrete", isFree: true },
    "Safety Protocols": { name: "Workplace Safety & OSHA Basics", provider: "Coursera", url: "https://www.coursera.org/learn/workplace-safety", isFree: false },
    "Machine Operation": { name: "Industrial Machine Operations", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Machine%20Operator", isFree: true },
    "Quality Check": { name: "Quality Assurance Foundations", provider: "LinkedIn Learning", url: "https://www.linkedin.com/learning/quality-assurance-foundations", isFree: false },
    "Assembly": { name: "Manufacturing & Assembly", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Assembly", isFree: true },
    "Welding": { name: "Certified Welder Course", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Welder", isFree: true },
    "Steel Fixing": { name: "Advanced Steel Fixing", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Steel%20Fixer", isFree: true },
    "Plumbing": { name: "Plumbing Basics", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Plumber", isFree: true },
    "Carpentry": { name: "Carpentry Fundamentals", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Carpenter", isFree: true },
    "Heavy Equipment Operation": { name: "Heavy Machinery Operations", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Heavy%20Equipment", isFree: true },
    "AutoCAD Basics": { name: "AutoCAD for Construction", provider: "Udemy", url: "https://www.udemy.com/course/autocad-2023-masterclass/", isFree: false },
    "Basic Electrical": { name: "Basic Electrical Wiring", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Electrician", isFree: true },
    "Wiring": { name: "Electrical Wiring & Circuits", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Wiring", isFree: true },
    "Painting": { name: "Interior & Exterior Painting", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Painter", isFree: true },
    "Surface Preparation": { name: "Surface Preparation Techniques", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Surface%20Preparation", isFree: true },
    "Pipe Fitting": { name: "Pipe Fitting & Plumbing", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Pipe%20Fitting", isFree: true },
    "CNC Operation": { name: "CNC Machining Fundamentals", provider: "Udemy", url: "https://www.udemy.com/course/cnc-machining/", isFree: false },
    "Textile Weaving": { name: "Textile Production Basics", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Textile", isFree: true },
    "Forklift": { name: "Forklift Operation & Safety", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Forklift", isFree: true },
    "Loading": { name: "Warehousing & Loading Techniques", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Loading", isFree: true },
    "Inventory": { name: "Inventory Management Basics", provider: "Coursera", url: "https://www.coursera.org/learn/supply-chain-management", isFree: false },
    "Sewing": { name: "Garment Sewing & Stitching", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Sewing", isFree: true },
    "Heavy Lifting": { name: "Ergonomics & Safe Lifting", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Safe%20Lifting", isFree: true },
    "Driving Assistance": { name: "Road Safety & Driving Assistance", provider: "Skill India", url: "https://www.skillindiadigital.gov.in/courses?search=Driving", isFree: true },
};

export const ALL_JOBS = [
    // Chennai
    {
        id: "static_1", title: "Construction Worker", company: "TN Builders Ltd",
        location: "Chennai", salary_min: 15000, salary_max: 25000,
        required_skills: ["Masonry", "Concrete Work", "Safety Protocols"],
        description: "Looking for energetic construction workers for a major residential project in Chennai. Must be comfortable working at heights and following safety protocols. Daily meals provided.",
        qualification: "8th Pass / Basic Literacy", experience: "1-3 Years",
        created_at: "2026-02-18T10:00:00Z",
        has_accommodation: true, has_food: true, has_transport: false, status: "active",
    },
    {
        id: "static_2", title: "Plumber", company: "Urban Build Co",
        location: "Chennai", salary_min: 16000, salary_max: 24000,
        required_skills: ["Plumbing", "Pipe Fitting", "Carpentry"],
        description: "Experienced plumbers needed for high-rise apartment maintenance. Should know PEX and PVC piping systems. Tools will be provided by the company.",
        qualification: "ITI in Plumbing preferred", experience: "2+ Years",
        created_at: "2026-02-19T09:30:00Z",
        has_accommodation: false, has_food: false, has_transport: true, status: "active",
    },
    {
        id: "static_3", title: "Electrician Helper", company: "Spark Solutions",
        location: "Chennai", salary_min: 14000, salary_max: 22000,
        required_skills: ["Basic Electrical", "Wiring", "Safety Protocols"],
        description: "Assist lead electricians in industrial wiring projects. Great opportunity for fresh ITI graduates to learn on the job. Safety gear is mandatory.",
        qualification: "10th Pass / ITI Pursuing", experience: "Fresher to 1 Year",
        created_at: "2026-02-17T14:20:00Z",
        has_accommodation: true, has_food: false, has_transport: true, status: "active",
    },
    {
        id: "static_4", title: "Painter", company: "Rainbow Interiors",
        location: "Chennai", salary_min: 13000, salary_max: 20000,
        required_skills: ["Painting", "Surface Preparation", "Quality Check"],
        description: "Interior and exterior painters required for commercial buildings. Must be skilled in spray painting and texture finishing. High attention to detail required.",
        qualification: "Literacy / Experience based", experience: "2-4 Years",
        created_at: "2026-02-20T11:15:00Z",
        has_accommodation: false, has_food: true, has_transport: false, status: "active",
    },
    // Coimbatore
    {
        id: "static_5", title: "Factory Operator", company: "Auto Parts Mfg",
        location: "Coimbatore", salary_min: 18000, salary_max: 28000,
        required_skills: ["Machine Operation", "Quality Check", "Assembly"],
        description: "Operate automated assembly lines for automotive components. 8-hour shifts with overtime options. Clean and safe working environment.",
        qualification: "Diploma / ITI", experience: "1-2 Years",
        created_at: "2026-02-19T08:00:00Z",
        has_accommodation: true, has_food: false, has_transport: true, status: "active",
    },
    {
        id: "static_6", title: "Welder", company: "Steel Structures Co",
        location: "Coimbatore", salary_min: 20000, salary_max: 30000,
        required_skills: ["Welding", "Steel Fixing", "Safety Protocols"],
        description: "MIG/TIG welders for structural steel fabrication. Must be able to read blue-prints. Certification is a big plus. Overtime pay included.",
        qualification: "ITI Welder Certification", experience: "3+ Years",
        created_at: "2026-02-18T16:45:00Z",
        has_accommodation: true, has_food: true, has_transport: false, status: "active",
    },
    {
        id: "static_7", title: "CNC Machine Operator", company: "Precision Works",
        location: "Coimbatore", salary_min: 22000, salary_max: 32000,
        required_skills: ["CNC Operation", "Machine Operation", "AutoCAD Basics"],
        description: "Operator needed for VMC and CNC machines. Should be able to do basic offset corrections and tooling changes. Immediate joining preferred.",
        qualification: "Diploma in Mechanical", experience: "2+ Years",
        created_at: "2026-02-20T10:00:00Z",
        has_accommodation: false, has_food: false, has_transport: true, status: "active",
    },
    {
        id: "static_8", title: "Textile Worker", company: "Kavi Textiles",
        location: "Coimbatore", salary_min: 12000, salary_max: 18000,
        required_skills: ["Textile Weaving", "Quality Check", "Machine Operation"],
        description: "Join our expanding textile unit. Roles available in weaving and quality inspection departments. Skill training provided for interested candidates.",
        qualification: "8th Pass / 10th Pass", experience: "Fresher Welcome",
        created_at: "2026-02-15T12:00:00Z",
        has_accommodation: true, has_food: true, has_transport: true, status: "active",
    },
    // Madurai
    {
        id: "static_9", title: "Warehouse Associate", company: "Logistics Hub",
        location: "Madurai", salary_min: 12000, salary_max: 20000,
        required_skills: ["Loading", "Inventory", "Forklift"],
        description: "Maintain stock levels and assist in loading/unloading of shipments. Should be familiar with basic inventory software and safety rules.",
        qualification: "10th Pass / Inter", experience: "1 Year",
        created_at: "2026-02-19T13:30:00Z",
        has_accommodation: false, has_food: true, has_transport: true, status: "active",
    },
    {
        id: "static_10", title: "Brick Layer", company: "South India Constructions",
        location: "Madurai", salary_min: 14000, salary_max: 22000,
        required_skills: ["Masonry", "Concrete Work", "Safety Protocols"],
        description: "Specialist bricklayers for traditional and modern construction projects. Strong physical stamina and teamwork skills are essential.",
        qualification: "Skill-based", experience: "2-5 Years",
        created_at: "2026-02-17T09:00:00Z",
        has_accommodation: true, has_food: true, has_transport: false, status: "active",
    },
];

